#!/usr/bin/env python3

'''
		######--------------CixoNotesConfig--------------#####

	Ten program odpowiada za przygotowanie konfiguracji dla dzialania cixo-notes
	dla uzytkownika ktury ten sktypt wywola
'''

import cixo_notes
from pathlib import Path
from configparser import ConfigParser

home = Path.home()

notes_folder = Path(str(home), "CixoNotes")
config = Path(str(home), ".config/cixo-notes.ini")

print(cixo_notes.language.get("cixo-notes-config", "CONFIG_FILE_HELLO").replace("||", "\n"))

if config.exists():
	if input(cixo_notes.language.get("cixo-notes-config", "CONFIG_FILE_EXIST")) == cixo_notes.language.get("cixo-notes", "CONFIRM_LETTER"):
		config.unlink()
	else:
		exit()
	
date_format = input(cixo_notes.language.get("cixo-notes-config", "DATE_FORMAT_CONFIG"))
date_format = date_format if date_format.split() != [] else "%Y-%m-%d"

#ini w ten sposon koduje %
date_format = date_format.replace("%", "%%")

notes_folder_input = input(cixo_notes.language.get("cixo-notes-config", "NOTES_DIR").format(default_source = str(notes_folder)))
if notes_folder_input.split() != []:
	notes_folder = Path(notes_folder_input) 
	
if notes_folder.exists() is False:
	print(cixo_notes.language.get("cixo-notes-config", "DIR_NOT_EXIST"))
	notes_folder.mkdir(parents = True)
		
new_file = ConfigParser()
new_file.add_section("cixo-notes")
new_file.set("cixo-notes", "DATE_FORMAT", date_format)
new_file.set("cixo-notes", "NOTES_DIRECTORY", str(notes_folder) + "/")

try:
	with config.open("w") as config_file:
		new_file.write(config_file)
	print(cixo_notes.language.get("cixo-notes-config", "GOOD_APP_CONFIG"))
	
except:
	print(cixo_notes.language.get("cixo-notes-config", "BAD_APP_CONFIG"))

